### PR TITLE
Update code for Stardew Valley 1.2 & simplify build config

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request...

* Updates the code for Stardew Valley 1.2.
* Updates the build config package & simplifies the build configuration.
* Changes the default root namespace to match the namespaces used.
* Standardises the `manifest.json`.

If the changes look fine, can you release [ImprovedQualityOfLife 1.1.1.zip](https://github.com/demiacle/QualityOfLifeMods/files/1347785/ImprovedQualityOfLife.1.1.1.zip)?

### CODE REVIEW

**Comment by demiacle** [comment]
been so busy, and out of the loop. Im out of town atm tho, ive seen some forks so i thought people had been updating and releasing on their own! How would you like to release this?

**Comment by Pathoschild** [comment]
@demiacle Can you release the [attached zip](https://github.com/demiacle/QualityOfLifeMods/files/1347785/ImprovedQualityOfLife.1.1.1.zip) to the [mod's Nexus page](https://www.nexusmods.com/stardewvalley/mods/1025)?

**Comment by demiacle** [comment]
Done!

**Comment by Pathoschild** [comment]
Can you also update the version number on the Nexus page? (SMAPI 2.0 uses it for update checks.)

**Comment by Pathoschild** [comment]
@demiacle Can you also update the version number on the Nexus page? (SMAPI 2.0 uses it for update checks.)

**Comment by demiacle** [comment]
Done! Anything else?

**Comment by Pathoschild** [comment]
That's all. Thanks!

**Comment by demiacle** [comment]
Cool! You do awesome work man! Thumbs up!

**Pull request merged**
